all:
  hosts:
    R1:
      ansible_host: 192.168.100.10
      ansible_connection: network_cli
      ansible_become: yes
      ansible_become_method: enable
      ansible_user: admin
      ansible_password: admin
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      ansible_network_os: eos
    R2:
      ansible_host: 192.168.100.11
      ansible_connection: network_cli
      ansible_become: yes
      ansible_become_method: enable
      ansible_user: admin
      ansible_password: admin
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      ansible_network_os: eos
    R3:
      ansible_host: 192.168.100.12
      ansible_connection: network_cli
      ansible_become: yes
      ansible_become_method: enable
      ansible_user: admin
      ansible_password: admin
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      ansible_network_os: eos
    R4:
      ansible_host: 192.168.100.13
      ansible_connection: network_cli
      ansible_become: yes
      ansible_become_method: enable
      ansible_user: admin
      ansible_password: admin
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      ansible_network_os: eos
